from random import randint
import tkinter
from tkinter import *
def select():
	x=int(Entry.get(e))
	y=int(Entry.get(e1))
	p=int(Entry.get(e2))
	z=randint(x,y)
	if(z==p): l.config(text="correct guess",fg="green")
	else: l.config(text="wrong guess",fg="red")
	la.config(text="generated random number is %d"%z)
	
window=tkinter.Tk()
window.title("guess")
window.geometry("500x500")
l1=tkinter.Label(text="enter the range of values min and max range")
e=tkinter.Entry(window)
e1=tkinter.Entry(window)
l2=tkinter.Label(text="enter your guess among your range")
e2=tkinter.Entry(window)
l=tkinter.Label(window,text="Result is")
b=tkinter.Button(window,text="select",command=select)
la=tkinter.Label(text="Generated random number is")
l1.pack()
e.pack()
e1.pack()
l2.pack()
e2.pack()
b.pack()
l.pack()
la.pack()
window.mainloop()
